# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-15 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('street', '0019_auto_20180115_0406'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPrayerMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, upload_to='upload_to_media')),
                ('video_image', models.ImageField(blank=True, upload_to='uploadto_video')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'UserMedia',
            },
        ),
    ]
